description:
  This section describes all of the services that may be present on the AP.
  Each service is then referenced via its name inside an interface, ssid, ...
type: object
properties:
  lldp:
    $ref: "https://ucentral.io/schema/v1/services/lldp/"
  ssh:
    $ref: "https://ucentral.io/schema/v1/services/ssh/"
  ntp:
    $ref: "https://ucentral.io/schema/v1/services/ntp/"
  mdns:
    $ref: "https://ucentral.io/schema/v1/services/mdns/"
  rtty:
    $ref: "https://ucentral.io/schema/v1/services/rtty/"
  log:
    $ref: "https://ucentral.io/schema/v1/services/log/"
  wifi-steering:
    $ref: "https://ucentral.io/schema/v1/services/wifi-steering/"
