description:
  Enable Hotspot 2.0 support.
type: object
properties:
  venue-name:
    description:
      This parameter can be used to configure one or more Venue Name Duples
      for Venue Name ANQP information.
    type: string
  venue-group:
    description:
      The available values are defined in 802.11u.
    type: integer
    maximum: 32
  venue-type:
    description:
      The available values are defined in IEEE Std 802.11u-2011, 7.3.1.34
    type: integer
    maximum: 32
  venue-url:
    description:
      This parameter can be used to configure one or more Venue URL Duples to
      provide additional information corresponding to Venue Name information.
    type: string
    format: uri
  auth-type:
    description:
      This parameter indicates what type of network authentication is used in
      the network.
    type: object
    properties:
      type:
        description:
          Specifies the specific network authentication type in use.
        type: string
        enum:
        - "terms-and-conditions"
        - "online-enrollment"
        - "http-redirection"
        - "dns-redirection"
      uri:
        description:
          Specifies the redirect URL applicable to the indicated authentication type.
        type: string
        format: uri
        examples:
        - https://operator.example.org/wireless-access/terms-and-conditions.html
        - http://www.example.com/redirect/me/here/
    minLength: 2
    maxLength: 2
  domain-name:
    description:
      The IEEE 802.11u Domain Name.
    type: string
    format: hostname
  nai-realm:
    description:
      NAI Realm information
    type: string
  osen:
    description:
      OSU Server-Only Authenticated L2 Encryption Network;
    type: boolean
  anqp-domain:
    description:
      ANQP Domain ID, An identifier for a set of APs in an ESS that share the
      same common ANQP information.
    type: integer
    maximum: 65535
    minimum: 0
  friendly-name:
    description:
      This parameter can be used to configure one or more Operator Friendly
      Name Duples.
    type: string
  icon:
    description:
      The operator icons.
    type: array
    items:
      type: object
      properties:
        width:
          type: integer
          description: The width of the operator icon in pixel
          examples:
          - 64
        height:
          type: integer
          description: The height of the operator icon in pixel
          examples:
          - 64
        type:
          type: string
          description: The mimetype of the operator icon
          examples:
          - image/png
        uri:
          type: string
          format: uri
          description: The URL the operator icon is available at
          examples:
          - http://example.org/operator-64x64.png
        language:
          type: string
          description: ISO 639-2 language code of the icon
          pattern: "^[a-z][a-z][a-z]$"
          examples:
          - eng
          - fre
          - ger
          - ita
      examples:
      - width: 32
        height: 32
        type: image/png
        uri: http://example.org/operator-32x32.png
        language: eng
      - width: 64
        height: 64
        type: image/png
        uri: http://example.org/operator-64x64.png
        language: eng
      - width: 16
        height: 16
        type: image/gif
        uri: data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7
        language: eng
