description:
  Describe the properties of a Radius server.
type: object
properties:
  host:
    description:
       The URI of our Radius server.
    type: string
    format: uc-host
    examples:
    - 192.168.1.10
  port:
    description:
       The network of our Radius server.
    type: integer
    maximum: 65535
    minimum: 1024
    examples:
    - 1812
  secret:
    description:
      The shared Radius authentication secret.
    type: string
    examples:
    - secret
  request-attribute:
    description:
      The additional Access-Request attributes that gets sent to the server.
    type: array
    items:
      type: string
    examples:
    - 126:s:Operator
  request-cui:
    description:
      This will enable support for Chargeable-User-Identity (RFC 4372).
    type: boolean
    default: false
