description:
  This section can be used to setup a persistent connection to a rTTY server.
type: object
properties:
  host:
    description:
      The server that the AP shal to connect to.
    type: string
    format: uc-host
    example:
    - 192.168.1.10
  port:
    description:
      This option defines the port that we connect to.
    type: integer
    maximum: 65535
    default: 5912
  token:
    description:
      The security token that we use to authenticate with the server.
    type: string
    maxLength: 32
    minLength: 32
    example:
    - 01234567890123456789012345678901
