$id: https://openwrt.org/ucentral.schema.json
$schema: http://json-schema.org/draft-07/schema#
description: OpenWrt uCentral schema
type: object
properties:
  unit:
    $ref: "https://ucentral.io/schema/v1/unit/"
  globals:
    $ref: "https://ucentral.io/schema/v1/globals/"
  definitions:
    $ref: "https://ucentral.io/schema/v1/definitions/"
  radios:
    type: array
    items:
      $ref: "https://ucentral.io/schema/v1/radio/"
  interfaces:
    type: array
    items:
      $ref: "https://ucentral.io/schema/v1/interface/"
  services:
    type: array
    items:
      $ref: "https://ucentral.io/schema/v1/service/"
  metrics:
    $ref: "https://ucentral.io/schema/v1/metrics/"
  config-raw:
    $ref: "https://ucentral.io/schema/v1/config-raw/"
